services:
  postgres:
    image: postgres:16
    container_name: postgres
    command: postgres -c listen_addresses='*'

    ports:
      - "0.0.0.0:5432:5432"

    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=db

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ..:/workspace

volumes:
  postgres_data:

